name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Disable Husky during the workflow
  HUSKY: 0

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=32768'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Create file
        run: |
          touch .env
          echo "FIREBLOCKS_API_SECRET_KEY_PATH=${{secrets.FIREBLOCKS_API_SECRET_KEY_PATH}}" >> .env
          echo "FIREBLOCKS_API_KEY=${{secrets.FIREBLOCKS_API_KEY}}" >> .env
          if [ -z "${{ secrets.FIREBLOCKS_BASE_URL }}" ]; then
            echo "FIREBLOCKS_BASE_URL=https://api.fireblocks.io" >> .env
          else
            echo "FIREBLOCKS_BASE_URL=${{ secrets.FIREBLOCKS_BASE_URL }}" >> .env
          fi
          if [ -z "${{ secrets.FIREBLOCKS_ASSET_ID }}" ]; then
            echo "FIREBLOCKS_ASSET_ID=HBAR_TEST" >> .env
          else
            echo "FIREBLOCKS_ASSET_ID=${{ secrets.FIREBLOCKS_ASSET_ID }}" >> .env
          fi
          if [ -z "${{ secrets.FIREBLOCKS_VAULT_ACCOUNT_ID }}" ]; then
            echo "FIREBLOCKS_VAULT_ACCOUNT_ID=2" >> .env
          else
            echo "FIREBLOCKS_VAULT_ACCOUNT_ID=${{ secrets.FIREBLOCKS_VAULT_ACCOUNT_ID }}" >> .env
          fi
          echo "FIREBLOCKS_HEDERA_ACCOUNT_PUBLIC_KEY=${{secrets.FIREBLOCKS_HEDERA_ACCOUNT_PUBLIC_KEY}}" >> .env
          echo "FIREBLOCKS_HEDERA_ACCOUNT_ID=${{secrets.FIREBLOCKS_HEDERA_ACCOUNT_ID}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_AUTHORIZATION_TOKEN=${{secrets.DFNS_SERVICE_ACCOUNT_AUTHORIZATION_TOKEN}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_PRIVATE_KEY_PATH=${{secrets.DFNS_SERVICE_ACCOUNT_PRIVATE_KEY_PATH}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_CREDENTIAL_ID=${{secrets.DFNS_SERVICE_ACCOUNT_CREDENTIAL_ID}}" >> .env
          if [ -z "${{ secrets.DFNS_APP_ORIGIN }}" ]; then
            echo "DFNS_APP_ORIGIN=http://stablecoin.es" >> .env
          else
            echo "DFNS_APP_ORIGIN=${{ secrets.DFNS_APP_ORIGIN }}" >> .env
          fi
          echo "DFNS_APP_ID=${{secrets.DFNS_APP_ID}}" >> .env
          if [ -z "${{ secrets.DFNS_BASE_URL }}" ]; then
            echo "DFNS_BASE_URL=https://api.dfns.ninja" >> .env
          else
            echo "DFNS_BASE_URL=${{ secrets.DFNS_BASE_URL }}" >> .env
          fi
          echo "DFNS_WALLET_ID=${{secrets.DFNS_WALLET_ID}}" >> .env
          echo "DFNS_WALLET_PUBLIC_KEY=${{secrets.DFNS_WALLET_PUBLIC_KEY}}" >> .env
          echo "DFNS_WALLET_HEDERA_ACCOUNT_ID=${{secrets.DFNS_WALLET_HEDERA_ACCOUNT_ID}}" >> .env

      - name: Test custodialwalletutils
        run: |
          npm run test:ci
