name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Disable Husky during the workflow
  HUSKY: 0

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: custodians-linux-medium
    env:
      NODE_OPTIONS: '--max-old-space-size=32768'
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Node Environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Create file
        run: |
          touch .env
          echo "FIREBLOCKS_API_SECRET_KEY=${{secrets.FIREBLOCKS_API_SECRET_KEY}}" >> .env
          echo "FIREBLOCKS_API_KEY=${{secrets.FIREBLOCKS_API_KEY}}" >> .env
          if [ -z "${{ secrets.FIREBLOCKS_BASE_URL }}" ]; then
            echo "FIREBLOCKS_BASE_URL=https://api.fireblocks.io" >> .env
          else
            echo "FIREBLOCKS_BASE_URL=${{ secrets.FIREBLOCKS_BASE_URL }}" >> .env
          fi
          if [ -z "${{ secrets.FIREBLOCKS_ASSET_ID }}" ]; then
            echo "FIREBLOCKS_ASSET_ID=HBAR_TEST" >> .env
          else
            echo "FIREBLOCKS_ASSET_ID=${{ secrets.FIREBLOCKS_ASSET_ID }}" >> .env
          fi
          if [ -z "${{ secrets.FIREBLOCKS_VAULT_ACCOUNT_ID }}" ]; then
            echo "FIREBLOCKS_VAULT_ACCOUNT_ID=2" >> .env
          else
            echo "FIREBLOCKS_VAULT_ACCOUNT_ID=${{ secrets.FIREBLOCKS_VAULT_ACCOUNT_ID }}" >> .env
          fi
          echo "FIREBLOCKS_PUBLIC_KEY=${{secrets.FIREBLOCKS_PUBLIC_KEY}}" >> .env
          echo "FIREBLOCKS_HEDERA_ACCOUNT_ID=${{secrets.FIREBLOCKS_HEDERA_ACCOUNT_ID}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_AUTHORIZATION_TOKEN=${{secrets.DFNS_SERVICE_ACCOUNT_AUTHORIZATION_TOKEN}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_PRIVATE_KEY=${{secrets.DFNS_SERVICE_ACCOUNT_PRIVATE_KEY}}" >> .env
          echo "DFNS_SERVICE_ACCOUNT_CREDENTIAL_ID=${{secrets.DFNS_SERVICE_ACCOUNT_CREDENTIAL_ID}}" >> .env
          if [ -z "${{ secrets.DFNS_APP_ORIGIN }}" ]; then
            echo "DFNS_APP_ORIGIN=http://stablecoin.es" >> .env
          else
            echo "DFNS_APP_ORIGIN=${{ secrets.DFNS_APP_ORIGIN }}" >> .env
          fi
          echo "DFNS_APP_ID=${{secrets.DFNS_APP_ID}}" >> .env
          if [ -z "${{ secrets.DFNS_BASE_URL }}" ]; then
            echo "DFNS_BASE_URL=https://api.dfns.ninja" >> .env
          else
            echo "DFNS_BASE_URL=${{ secrets.DFNS_BASE_URL }}" >> .env
          fi
          echo "DFNS_WALLET_ID=${{secrets.DFNS_WALLET_ID}}" >> .env
          echo "DFNS_WALLET_PUBLIC_KEY=${{secrets.DFNS_WALLET_PUBLIC_KEY}}" >> .env
          echo "DFNS_WALLET_HEDERA_ACCOUNT_ID=${{secrets.DFNS_WALLET_HEDERA_ACCOUNT_ID}}" >> .env
          echo "DFNS_WALLET_ID_ECDSA=${{secrets.DFNS_WALLET_ID_ECDSA}}" >> .env
          echo "DFNS_WALLET_HEDERA_ACCOUNT_ID_ECDSA=${{secrets.DFNS_WALLET_HEDERA_ACCOUNT_ID_ECDSA}}" >> .env
          echo "DFNS_WALLET_PUBLIC_KEY_ECDSA=${{secrets.DFNS_WALLET_PUBLIC_KEY_ECDSA}}" >> .env

      - name: Test custodialwalletutils
        run: |
          npm run test:ci
